updated OneLogin to v3p 7.2 compliant
silverstripe/silverstripe-saml pull request #14
Opened 2018-11-05 03:50 UTC by Alastairkn

updated OneLogin to v3 which has removed mcrypt which will make this module php 7.2 compliant

2018-11-05 03:59 UTC, NightJar approved these changes
Looks really good, just a few minor formatting tidies please :)
This is really awesome, thanks for contributing!

2018-11-05 03:59 UTC, NightJar commented on src/Control/SAMLController.php
> +        /** @var \OneLogin\Saml2\Auth $auth */
`Auth` is sufficient here, as opposed to the FQCN.

2018-11-05 03:59 UTC, NightJar commented on src/Control/SAMLController.php
> +            /** @var OneLogin\Saml2\Auth $auth */
As earlier, the namespace is unnecessary, as the class is imported above (`use ...`)

2018-11-05 03:59 UTC, NightJar commented on src/Control/SAMLController.php
> +                throw new \OneLogin\Saml2\Error(
Please import the class (`use OneLogin\Saml2\Error;`) and use the unqualified classname here.

2018-11-05 03:59 UTC, NightJar commented on src/Control/SAMLController.php
> +                    \OneLogin\Saml2\Error::METADATA_SP_INVALID
and here - unqualify the classname via use statements please

2018-11-05 03:59 UTC, NightJar commented on src/Helpers/SAMLHelper.php
> +     * @return OneLogin\Saml2\Auth
```diff
- OneLogin\Saml2\Auth
+ Auth
```

2018-11-05 03:59 UTC, NightJar commented on src/Control/SAMLController.php
> +     * @throws OneLogin\Saml2\Error
please just use `Error` once you've added the `use` statement (see other comments)

2018-11-05 03:59 UTC, NightJar requested changes
whoops, accidentally approved instead of requesting changes

2018-11-05 04:17 UTC, Alastairkn commented
No worries, i'll make the changes you've said and make a new pull request

I did wonder about the fqcn.

2018-11-05 11:17 UTC, madmatt commented
Oooh yay thanks for this @Alastairkn, I was wanting to do this as well but when we used the module they hadn't released v3 yet stable and the testing branch for it was a bit broken.

+1 for merging this one in as soon as the changes have been made as @NightJar requested, and then tagging `1.0.0` to get a stable version released IMO.

2018-11-05 23:28 UTC, NightJar approved these changes
Most excellent, thanks for this!

2018-11-05 23:28 UTC, merged

2018-11-05 23:28 UTC, NightJar commented
So tag `1.0.0` your reckon @madmatt ?

2018-11-05 23:29 UTC, NightJar commented
Oooh, this also closes #12 - yay \o/

2018-11-05 23:39 UTC, NightJar commented
@Alastairkn @madmatt I've tagged `1.0.0` :)

@madmatt I don't have context over what is included in this, so if you have a spare moment it'd be awesome if you could [add some release notes](https://github.com/silverstripe/silverstripe-saml/releases/edit/1.0.0) 👍

2018-11-06 09:00 UTC, madmatt commented
Perfect, thanks @NightJar. I've updated the release notes now :)